name: Build FlyDog SDR Image

on:
  schedule:
  - cron: 0 20 * * *
  release:
    types: published
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Compile firmware
      id: compile
      run: |
        sudo ./wizard.sh
        echo "::set-output name=status::success"

    - name: Upload image
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success'
      with:
        name: FlyDog_SDR_IMG
        path: builder/deploy
