name: Build Raspbian

on:
  release:
    types: published
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Compile
      id: compile
      run: |
        sudo bash wizard.sh
